version: "3.8"
services:
  discord-bot:
    build: .
    env_file: .env.docker
    volumes:
      - .:/app
      - /app/node_modules
      - sqlite-data:/app/sequelize/database
    restart: unless-stopped

volumes:
  sqlite-data:
